### PR TITLE
Dev final version exceptions

### PR DESCRIPTION
**Pull request by AnderGoiri**
Good morning. I've made some changes:

Exception Handling:

- Revamped the code to handle exceptions.

Javadoc Updates:

- Added detailed Javadoc comments to make the code easier to understand and maintain.

Take a look and let me know what you think!

Cheers

### CODE REVIEW

**Review by sunder-012 — APPROVED** [review]
Everything ok, all classes with javadoc.

**Comment by ysasgon** [comment]
I read the files and i think they are alright. Nice job.

**Comment by olaialor** [comment]
Everything is ok.

**Comment by AnderGoiri** [comment]
Greenlight to the merge

**Pull request merged**
